language: node_js
node_js:
- 4.2.2
before_script:
- npm install
after_success:
- "./node_modules/hexo/bin/hexo clean"
- "./node_modules/hexo/bin/hexo generate"
deploy:
  provider: s3
  bucket: milesmaddox.com
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-west-2
  access_key_id:
    secure: "UgUgF6dNK0O7KP2K4JFRIAuCIJ55dASGFgD4NTiP8zlRfU9JsOTgC1FRbTuB4gn0GPgWczTXAaq2mvWEz+1yipme/M2FzSOvgpVWmFV5m5t/jdrDhFT4JMO8g1BkY42qse4+apWUtol1rJw/hBEc2Z3q2vh5bhAwtXrvZdaaMCas5Rft4p0DOe4+mH2wQkv4jr05gzVNLKz2dFltU4xJA8BCxGTz6IvfhVOTE3O2iVCp0eqyqyg9nuW5dguID+3c+MKH2cvANVFhz4pUh3IJF+YbNauhXQZ+XQ5JmvS9Cvh0auQyTXSNLZ6cZCFjPlKwGS8pZ1iGVcDGlDfYFxQPfps/6SMtIzWzoMs6gzycOtC95XVjA9HrCuV5Vr2d1yto8NRsseWBUsEIkMkCIGOV6BnRkrJvNP5TsxNol9WKaoyIKVh2udW4TRD/S3Lg4s/56xz6ET7zcyIfAbezIRnZjXCjxobOwaIBUGPd+EhLEZ6/KLP4DNKQHtHzBD+14glUll3dtVieRuOVt5DJclTly35nVDxJ+BocipuLuU2Z6CxNM4hO/tlbmjBX9teh0GZABvlrxPmLHAj7zRymtwExpzME/pt8KlH7DLvH6j/EyLKPmmuIMZCaoYqEVpOHMoiyi2+k0B3+6JB8kx+jEmc3p+V+9LpjIt3rT2ld/l/CvzQ="
  secret_access_key:
    secure: "IKggRArqjzdZwWGJwoF4I6Esw4MA3ZiC0VZcMu0KNcm7AnQ9AQBGPS+FT7GCNTxhLVvdiMr5iSf6kUtjCMkmBJOagiGyapkZqYGCgufJZ6/9dcSNP973o01Xkv2JFEUxMCrab9DbsL0IpIO+Kqz101b5duo68ELwg5FXDExal+LOI0Hb2C1tx3E0jx3py0uNGCvXfUfyAPMyuWm+Zr1L8a9VgqJ3olfeMTejhIfG0SDrpePBILPk0rY69UvUXwwwdVi88wFJpMg2RYMS1Wqxloer9aldSgjpc5+3+/qBQy8EwARRzR5T1bXe/Srg/B0opOgVf6Xhsi7U/SX6/jGhwjCKY/BDmLcJRJ/PcoANIbRxH41u+rRTZUVs0HtJD/WQBgfwarTFqmrtGqGs30pWseg9736QwV2IQqqGGMpOfixGBMnO+QOdqjNpHPAbkQ8o7tWg1dmZ8LDEP5a7OiWovTMAmP0gFmimviCxoOv80OLLLpZi0MHtavdjf+bHulONhhm/JLuZOFe2HgfELptMnJf57eQBXwXDCOOWbUfWPFMx/HNYzo6/UGEhx7LSOyOUyhOs/steuXnZWrnWCelNeeAZv5VVvEQjnsZZL3ZBgmOp/mzDnOyMAi4e6eK1LdvvBfCslE+sUNZ5EWmJmhPZ39lhsbIAcDKmt3DL/idXV+0="
