language: node_js
node_js:
- 6.14.4
before_script:
- npm install
after_success:
- "./node_modules/hexo/bin/hexo clean"
- "./node_modules/hexo/bin/hexo generate"
deploy:
  provider: s3
  bucket: milesmaddox.com
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-west-2
  access_key_id:
    secure: "km9DtAt46xm6HiXDXfZ4JcmdqVYUEvkcyDg3koi/SmUvhuAGdhnFw5XDjWPm2FqvrPrFc5qU83fm4oYuUiyU5Fp4DAEW0spOdWMbS+RTN2ZjvDRMcJTzpLR3kgb3FryRsirbP5vLrAnJVj4xpdGUE3Kx/OXWWDtO+2oAzdic8lh0PkTPOeIWyZFLNCdsmhbMDqHBtulE1aryIHwi7XyYPtu+dW7B/XVH5YqrRkSvm9SPFX170QmX1k1Pf4HALplaT+uWuPL92AmtQ0uQHpGsUmRzOQQrGc+r+h0q1lMe9himn71xtFZgTV1TwKqMtYnU2USsppqIE8V2DzpYnazsUlzdEWSrejQ4orYNkVDatudlSgUhjsaimT5PgNZ9nJi6cZILk92zF5JOdeKx0w5kyRIIjavB5A87G66pslEmKN5QMUZsFtV8PSr+hcJQB5N3Tltb7HOYTnFx/ZuTLIXW9/AMVARJny9q5k9rY8CoMYPWIBnm1yZBOhszpN4F44YVPLCYdVLayoqzv8vxfN1R5GBGnEBnp39ZKHMy9CXQgTg6mnNy8ArpYLIAPzCciu/XkWCd2zoMhTr6i2kp7Rvc+MnEtqagaU4WohLe24zWf2KVwPy0BmsVHMY00Nr4728b2dg7dUv+asAMhdrCmt9ci4OPPtycKGPojB7Nc3E9ADw="
  secret_access_key:
    secure: "M4keVB8AxeM6BA1Zf5bDhBGhYhw5v7zKKpeJZdVRYDhUJC9jydEJyeR9xd5i1xgji3jD2O6SbeVnv4lJmWpPqm3NhzEvGsZcz1vbILcNdbLZMeLeNjU7goDJMV25M6cSSqZxLRbYv3LqbKnGLqG++AHVdxIhUqkSMbwh6C37usz9OwZdPI+EX8WBHsbgt1+wt91XFcx5Kt2vNJE7utEtITpFLVw+p3GGdaJaJ2kvSoUGI+5Q91era7IUt9QDl45P8yA/xaMdLY2q+auomNWW76Msf34bzR5lRRDQ2QU4W0fTsi9Ez8g5OOj8QAprz9oAEHkeYCL03Ip9yhMcCJpZo14D/jRsTsBH3AJ9IHCxnxuJTYHGhjCm9yb/TTijJFrn7G3djnzUrP0YNDVEJCGKcWgOkFKYPNMl6+AnfHN08XwlN7kgqWBKMqijPPLvjXAP61N0nmmoLjgRlBdkPryNdkmUzKTYINKs0T+6QWUvIfIL1VAb79EneI/0rgAoVKVVh7QlomWTACTj4Uf2W/BPfoKc9bCrACs2Haw6nEDAMlOKtL19cIyTRh3mwQYGm/XNmv31VK7BqiefiDQYtNOfbPJgTi4XzYvGq6wdazjwH5DOcpPLII3yaMW30r0vINXdhHkJEuOVJjTkjJeGrM5zoxasJH7C//85ydIQHaPcNvI="
