language: node_js
node_js:
- 4.2.2
before_script:
- npm install
after_success:
- "./node_modules/hexo/bin/hexo clean"
- "./node_modules/hexo/bin/hexo generate"
deploy:
  provider: s3
  bucket: blog.milesmaddox.com
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-west-2
  access_key_id:
    secure: wRWjuWLCLFBBfVQAvEa86P8n9ScduMZ+zLPMLlP30qHrZREldsqb/FYxozO0ywkatfMDsAtfOITRhfwd1LLtImAKbpfrEkg1v/x9GfelmaclWrShtPOLosBWPRTDFFJ3BiJntZzkjfBJfgyFczett/QEzTGTjALeHUuS5O4DHMekNoX2Say2RZ/7/rvXY0A5FuTzZXdAT86bpX/tQub2GnNJUfVD6Rg6Oz70KXk7fXBfAgBBTq/NfNOuli7ZDQucOBECpgTjPlskhcTm9EDBKv1ERqxKCB9lfv85W37cRQxgC3u5scZjK5ErJkP+FjyhdAZj5zwld8ZpKpcZ9X+5RGJz+Ov2SH01XvEFBo5gfHnYI84KQGgGkyRZk90FSpKkjio+ifiyl4VlTkAEemDqs1cXt8HzDrK52RKVhjtsp0Vu2M2vh+upSonATLegaE9BSQcMsEpOH0+PYYBSOph1iXhLsd+g/vEsATDO4KaCxrtQsjF+YNr2JDZz8Id3PKz2e0r87z0eolLVlkdPM+7RhreRNVmPCIFoFr3ch9udHRJFHoRK/Fl7F6LKaRde/EnPvAH9Hwen2BmYQDER2HPm46E2qOJtofG2zyPfKFqkGSjmWpitcgueMroha1FYKi73UO8pBRYbT0pyA+r3QS3D5mezIiKeRBpMhihQ9eiBImw=
  secret_access_key:
    secure: TQWb4x6vlTYoQdrpvQqkxWvWG9MZa81MIlp4IGPbtbAYOAR58yAqoDMjSZxfMLVn3fN5Ky/AR3P6XOidNt9Vatks9iEnqJ3ENsEbZLztzC+iw0P9XtmCFGlKOIk75Nz9oVkTota91NhVQDfQqqQKZYLixuNCJWP6FYtdUpIYjZOi3BpUJtwGIvCZ8mzHO83ETGgpbgpi9rHTGFImnd52Qtnx73cFMciyeyfw5pDFF4AfyWOJbbC5Mvdtt1bvTgWU8aIoo2ZKQ5127mcOlAf5lmuP5IVCn94CN17utaBHlS6IndLcSocFWUzXw6yc3w6+W39KknEcKojRW5M9drp0PnRAlvXAWVLrkhcVTK8Bifn/eCPRp9OxIz4pv5LxOICswlEzqK76j4RA528TGQ9cLzm4pi3p528pZW+7muVi32UGG3daP/OD4AbQyws1f3BNeYD5tCNwvEzGx8dOQIvmigjYRHIPbCZDxLVp8jCK7hr3Sd/vlzggrpQ7MODuDl7ruSeAsgC0nco4cSgIAkZAe6uiYhw/JNT6SMRpHkKKUgDXxCaikjJUCvYnxswqs97qWCNjwoC8Jjt/CCOc4sLFTuDv05dLXihsG1CuT7ks/JqhxCXQEF6Es1jEXzI3AHs9fucBPgRUTMUYu6xrENW/xmrbTP5nr3R9n2QAsatLlG0=
